routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('auth.login');
});

// Auth::routes();
require __DIR__ . '/auth.php';

// Route::get('/', 'HomeController@index');
Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', 'HomeController@index')->name('home');

    Route::group(['prefix' => 'order'], function () {
        Route::name('order.')->group(function () {
            // Route::get('/ordenes', 'OrderController@index');
            Route::get('order/{id_orden}', 'OrderController@show')->name('show');
            Route::get('/orders/get-orders', 'OrderController@getOrders')->name('data');
            Route::post('/order/factura', 'OrderController@facturar')->name('facturar');
            Route::post('/order/cancel', 'OrderController@cancelOrder')->name('cancel');
            Route::post('/send-hermes', 'OrderController@sendToHermes')->name('hermes');
            Route::get('/order/fechas', 'CancelationController@cancelation')->name('cancelation');
            Route::post('/order/add-hermesid', 'OrderController@addHermesId')->name('hermesid');
            Route::post('/order/add-rfc', 'OrderController@addRFC')->name('add-rfc');
            Route::get('/resend-webhook', 'OrderController@resendWebHook');
            Route::post('notacredito', 'OrderController@notacredito')->name('notacredito');
            Route::post('/creditNote', 'OrderController@creditNote')->name('gen_nc');
            Route::get('/{orderId}/nota-credito/{folio}', 'OrderController@showCreditNote')->name('show_nc');
            Route::post('/download', 'SoapController@download')->name('download');
            Route::post('/order/update-date', 'OrderController@updateDateOrder')->name('updateDate');
            
        });
        Route::group(['prefix' => 'address'], function () {
            Route::name('address.')->group(function () {
                Route::get('/address/{id}', 'AddressController@edit')->name('edit');
                Route::put('/address/{id}', 'AddressController@update')->name('update');
            });
        });
        Route::post('/product/delete', 'ProductController@delete')->name('product.delete');
    });

    Route::prefix('products')->group(function () {
        Route::name('product.')->group(function () {
            Route::get('/list-feed', 'ProductFeedController@index')->name('feed');
            Route::get('/get-feed-products', 'ProductFeedController@getDataProducts')->name('data');
            Route::get('/product-feed/export/csv', 'ProductFeedController@export_csv')->name('export_feed.csv');
            Route::get('/product-feed/export/excel', 'ProductFeedController@export_excel')->name('export_feed.excel');
        });
    });

    Route::prefix('categories')->group(function () {
        Route::name('category.')->group(function () {
            Route::get('/', 'GoogleCategoryController@index')->name('index');
            Route::get('/edit/{id}', 'GoogleCategoryController@edit')->name('edit');
            Route::get('/create', 'GoogleCategoryController@create')->name('create');
            Route::post('/store', 'GoogleCategoryController@store')->name('store');
            Route::put('/update/{id}', 'GoogleCategoryController@update')->name('update');
            Route::get('/get-categories', 'GoogleCategoryController@getCategories')->name('data');
        });
    });

    Route::group(['middleware' => ['role:Super Admin']], function () {
        Route::group(['prefix' => 'user'], function () {
            Route::name('user.')->group(function () {
                Route::get('/all', 'UserController@index')->name('list');
                Route::get('/create', 'UserController@create')->name('create');
                Route::post('/store', 'UserController@store')->name('store');
                Route::get('/edit/{id}', 'UserController@edit')->name('edit');
                Route::put('/update/{id}', 'UserController@update')->name('update');
                Route::delete('/delete', 'UserController@destroy')->name('destroy');
            });
        });
    });

    Route::get('buscar', 'OrderController@buscar')->name('search');

// Route::get('/n3YnkUWXXhUktQhP8PLH', function () {
    //     Artisan::call('canclation:cron');
    //     return 'OK';
    // });

    Route::get('/newsletter', 'NewsletterController@index')->name('newsletter');
    Route::get('/newsletter/old', 'NewsletterController@oldRegisters')->name('newsletter.old');
    Route::get('/newsletter/get-registers', 'NewsletterController@getRegisters')->name('newsletter.data');
    Route::get('/newsletter/get-registers-old', 'NewsletterController@getNewsletter')->name('newsletter.data.old');

    Route::get('qry', 'OrderController@address');

});
Route::get('/w0nXLI2WgFrCdycwvFaJ', 'CancelationController@Cancelar');
Route::get('/sin-hermesid', 'OrderController@sendHermesData');
Route::get('/ade921176492a307745bf24a8e055a3a', 'ChatBotController@getProductsFeed');

app/User.php
<?php

namespace App;

use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPass($password)
    {
        if (!empty($password)){
            $this->password = Hash::make($password);
            return $this;
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $user = new User($request->except('password'));
            $user->setPass($request->password);
            $user->save();

            $user->assignRole($request->role);

            return back()->with('success', 'Usuario creado exitosamente.');
        } catch (\Exception $th) {
            Log::debug($th);
            return back()->with('error', 'Error al crear el usuario.');
        }
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $user = User::findOrFail($id);
            $user->setPass($request->password);
            $user->update($request->except('password'));
            
            $user->syncRoles($request->role);

            return redirect()->route('user.list')->with('success', 'Usuario actualizado correctamente');
        } catch (\Throwable $th) {
            return back()->with('error', 'No se pudo actualizar el usuario.');
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        try{
            $user = User::find($request->id);
            if ($user->id == 1){
                return response()->json([
                    'ok' => false, 
                    'icon' => 'warning',
                    'msg' => 'No tienes permisos para realizar esta acción.'
                ], 200);
            }
            $user->syncRoles([]);
            $user->syncPermissions([]);
            $user->delete();
            return response()->json([
                'ok' => true, 
                'icon' => 'success',
                'msg' => 'Usuario eliminado correctamente.'
            ], 200);
        }catch (\Exception $exception){
            return response()->json([
                'ok' => false, 
                'icon' => 'warning',
                'msg' => 'Intente nuevamente o comuniquese con el administrador.'
            ], 200);
        }
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
<section class="col-md-4 offset-md-4 card">
    @if(session()->has('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ session()->get('success') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-hidden="true" aria-label="Close"></button>
    </div>
@elseif(session()->has('error'))
    <div class="alert alert-danger">
        {{ session()->get('error') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-hidden="true" aria-label="Close"></button>
    </div>
@endif
    <header class="card-header">
        <h2 class="card-title">Usuarios</h2>
    </header>
    <div class="card-body">
        <form action="{{ route('user.store') }}" method="post" class="form-horizontal">
            @csrf
            <div class="form-group row pb-3">
                <label class="col-sm-4 control-label text-sm-end pt-2">Usuario:</label>
                <div class="col-sm-8">
                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"  value="{{ old('name') }}">
                    @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
            <div class="form-group row pb-3">
                <label class="col-sm-4 control-label text-sm-end pt-2">Correo:</label>
                <div class="col-sm-8">
                    <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}">
                    @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
            <div class="form-group row pb-3">
                <label class="col-lg-4 control-label text-lg-end pt-2">Rol:</label>
                <div class="col-lg-8">
                    <select name="role" class="form-control populate">
                            <option value="Moderador">Moderador</option>
                    </select>
                </div>
            </div>
            <div class="form-group row pb-3">
                <label class="col-sm-4 control-label text-sm-end pt-2">Contraseña:</label>
                <div class="col-sm-8">
                    <input type="password" name="password" class="form-control @error('password') is-invalid @enderror">
                    @error('password')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
            <footer class="card-footer text-end">
                <button class="btn btn-primary">Crear</button>
            </footer>
        </form>
    </div>
</section>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<section class="col-md-4 offset-md-4 card">
    <header class="card-header">
        <h2 class="card-title">Usuarios</h2>
    </header>
    <div class="card-body">
      <form action="{{ route('user.update', $user->id) }}" method="post" class="form-horizontal">
        @csrf
        @method('PUT')
        <div class="form-group row pb-3">
            <label class="col-sm-4 control-label text-sm-end pt-2">Usuario:</label>
            <div class="col-sm-8">
                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"  value="{{ $user->name ? $user->name : old('name') }}">
                @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <div class="form-group row pb-3">
            <label class="col-sm-4 control-label text-sm-end pt-2">Correo:</label>
            <div class="col-sm-8">
                <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ $user->email ? $user->email : old('email') }}">
                @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <div class="form-group row pb-3">
            <label class="col-lg-4 control-label text-lg-end pt-2">Rol:</label>
            <div class="col-lg-8">
                <select name="role" class="form-control populate">
                        <option value="Moderador">Moderador</option>
                </select>
            </div>
        </div>
        <div class="form-group row pb-3">
            <label class="col-sm-4 control-label text-sm-end pt-2">Contraseña:</label>
            <div class="col-sm-8">
                <input type="password" name="password" class="form-control @error('password') is-invalid @enderror">
                @error('password')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <footer class="card-footer text-end">
            <button class="btn btn-primary">Actualizar</button>
        </footer>
    </form>
    </div>
</section>

@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<section class="col-md-8 offset-md-2 card mb-2">
    <div class="card-body">
        <a href="{{ route('user.create') }}" class="btn btn-success btn-small">Nuevo</a>
    </div>
</section>
<section class="col-md-8 offset-md-2 card">
    @if(session()->has('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ session()->get('success') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-hidden="true" aria-label="Close"></button>
    </div>
@elseif(session()->has('error'))
    <div class="alert alert-danger">
        {{ session()->get('error') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-hidden="true" aria-label="Close"></button>
    </div>
@endif
    <header class="card-header">
        <div class="card-actions">
            {{-- <a href="#" class="card-action card-action-toggle" data-card-toggle=""></a>
            <a href="#" class="card-action card-action-dismiss" data-card-dismiss=""></a> --}}
          
        </div>

        <h2 class="card-title">Usuarios</h2>
    </header>
    <div class="card-body">
        <table class="table table-responsive-md mb-0">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Uusario</th>
                    <th>correo</th>
                    <th>Rol</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $i=>$user)
                <tr>
                    <td>{{ $i+1 }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>@foreach ($user->roles as $role) {{$role->name}} @endforeach</td>
                    <td class="actions">
                        <a href="{{ route('user.edit', $user->id) }}"><i class="fas fa-pencil-alt"></i></a>
                        <a href="#" onclick="deleteUser({{$user->id}})" class="delete-row"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</section>

@endsection
@push('scripts')
<script type="text/javascript">
    function deleteUser(id)
    {
        var csrf_token = $('meta[name="csrf-token"]').attr('content');
        Swal.fire({
            title: "Eliminar Usuario",
            text: "¿Seguro de querer eliminar a este usuario?",
            icon: "warning",
            showCancelButton: true,
            confirmButtonText: 'Aceptar',
            showLoaderOnConfirm: true,
            preConfirm: (option) => {
                let data = {
                    id: id,
                    csrf_token: csrf_token,
                    _method: 'DELETE'
                };
                return fetch('{{ route('user.destroy') }}', {
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    },
                    method: 'POST',
                    body: JSON.stringify(data)
                })
                .then(response => {
                    if (!response.ok) {
                        throw new Error(response.statusText)

                    }
                    return response.json()
                })
                .catch(error => {
                    Swal.showValidationMessage(
                        `Request failed: ${error}`
                    )
                })
            },
            allowOutsideClick: () => !Swal.isLoading()
        }).then((result) => {
            if (result.isConfirmed) {
                    console.log(result)
                    Swal.fire({
                        icon: `${result.value.icon}`,
                        title: `${result.value.msg}`,
                        allowOutsideClick: false,
                        allowEscapeKey: false,
                    }).then((result) => {
                        // Reload the Page
                        location.reload();
                    });
                }
        });
    }
  </script>
@endpush