routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('auth.login');
});

// Auth::routes();
require __DIR__ . '/auth.php';

// Route::get('/', 'HomeController@index');
Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', 'HomeController@index')->name('home');

    Route::group(['prefix' => 'order'], function () {
        Route::name('order.')->group(function () {
            // Route::get('/ordenes', 'OrderController@index');
            Route::get('order/{id_orden}', 'OrderController@show')->name('show');
            Route::get('/orders/get-orders', 'OrderController@getOrders')->name('data');
            Route::post('/order/factura', 'OrderController@facturar')->name('facturar');
            Route::post('/order/cancel', 'OrderController@cancelOrder')->name('cancel');
            Route::post('/send-hermes', 'OrderController@sendToHermes')->name('hermes');
            Route::get('/order/fechas', 'CancelationController@cancelation')->name('cancelation');
            Route::post('/order/add-hermesid', 'OrderController@addHermesId')->name('hermesid');
            Route::post('/order/add-rfc', 'OrderController@addRFC')->name('add-rfc');
            Route::get('/resend-webhook', 'OrderController@resendWebHook');
            Route::post('notacredito', 'OrderController@notacredito')->name('notacredito');
            Route::post('/creditNote', 'OrderController@creditNote')->name('gen_nc');
            Route::get('/{orderId}/nota-credito/{folio}', 'OrderController@showCreditNote')->name('show_nc');
            Route::post('/download', 'SoapController@download')->name('download');
            Route::post('/order/update-date', 'OrderController@updateDateOrder')->name('updateDate');
            
        });
        Route::group(['prefix' => 'address'], function () {
            Route::name('address.')->group(function () {
                Route::get('/address/{id}', 'AddressController@edit')->name('edit');
                Route::put('/address/{id}', 'AddressController@update')->name('update');
            });
        });
        Route::post('/product/delete', 'ProductController@delete')->name('product.delete');
    });

    Route::prefix('products')->group(function () {
        Route::name('product.')->group(function () {
            Route::get('/list-feed', 'ProductFeedController@index')->name('feed');
            Route::get('/get-feed-products', 'ProductFeedController@getDataProducts')->name('data');
            Route::get('/product-feed/export/csv', 'ProductFeedController@export_csv')->name('export_feed.csv');
            Route::get('/product-feed/export/excel', 'ProductFeedController@export_excel')->name('export_feed.excel');
        });
    });

    Route::prefix('categories')->group(function () {
        Route::name('category.')->group(function () {
            Route::get('/', 'GoogleCategoryController@index')->name('index');
            Route::get('/edit/{id}', 'GoogleCategoryController@edit')->name('edit');
            Route::get('/create', 'GoogleCategoryController@create')->name('create');
            Route::post('/store', 'GoogleCategoryController@store')->name('store');
            Route::put('/update/{id}', 'GoogleCategoryController@update')->name('update');
            Route::get('/get-categories', 'GoogleCategoryController@getCategories')->name('data');
        });
    });

    Route::group(['middleware' => ['role:Super Admin']], function () {
        Route::group(['prefix' => 'user'], function () {
            Route::name('user.')->group(function () {
                Route::get('/all', 'UserController@index')->name('list');
                Route::get('/create', 'UserController@create')->name('create');
                Route::post('/store', 'UserController@store')->name('store');
                Route::get('/edit/{id}', 'UserController@edit')->name('edit');
                Route::put('/update/{id}', 'UserController@update')->name('update');
                Route::delete('/delete', 'UserController@destroy')->name('destroy');
            });
        });
    });

    Route::get('buscar', 'OrderController@buscar')->name('search');

// Route::get('/n3YnkUWXXhUktQhP8PLH', function () {
    //     Artisan::call('canclation:cron');
    //     return 'OK';
    // });

    Route::get('/newsletter', 'NewsletterController@index')->name('newsletter');
    Route::get('/newsletter/old', 'NewsletterController@oldRegisters')->name('newsletter.old');
    Route::get('/newsletter/get-registers', 'NewsletterController@getRegisters')->name('newsletter.data');
    Route::get('/newsletter/get-registers-old', 'NewsletterController@getNewsletter')->name('newsletter.data.old');

    Route::get('qry', 'OrderController@address');

});
Route::get('/w0nXLI2WgFrCdycwvFaJ', 'CancelationController@Cancelar');
Route::get('/sin-hermesid', 'OrderController@sendHermesData');
Route::get('/ade921176492a307745bf24a8e055a3a', 'ChatBotController@getProductsFeed');

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-xl-6  offset-md-3">
        <!-- Page Header -->
        <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
            <h1 class="page-title fw-semibold fs-18 mb-0">Productos Google/Facebook</h1>
            <div class="ms-md-1 ms-0">
                <nav>
                    <ol class="breadcrumb mb-0">
                        <li class="breadcrumb-item"><a href="#">Dashboards</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Productos</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-6  offset-md-3">
        <div class="card custom-card">
                <div class="card-header justify-content-between">
                    <div class="card-title">
                        Crear Categorias
                    </div>
                </div>
            <div class="card-body">
                <form action="{{ route('category.store') }}" method="POST">
                    @csrf
                    <div class="row mb-3">
                        <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Codigo ID Google</label>
                        <div class="col-sm-3">
                            <input type="number" name="id_google" class="form-control form-control-sm" id="colFormLabelSm" value="{{ old('id_google') }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Categorias <br><sub>Separadas por comas</sub></label>
                        <div class="col-sm-10">
                            <textarea name="categories" id="categories" cols="50" rows="10"  class="form-control form-control-sm" pattern="^[0-9a-zA-Z]+(,[0-9a-zA-Z]+){0,11}$">{{ old('categories') }}</textarea>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{{ route('category.index') }}" class="btn btn-default">Volver</a>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-xl-6  offset-md-3">
        <!-- Page Header -->
        <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
            <h1 class="page-title fw-semibold fs-18 mb-0">Productos Google/Facebook</h1>
            <div class="ms-md-1 ms-0">
                <nav>
                    <ol class="breadcrumb mb-0">
                        <li class="breadcrumb-item"><a href="#">Dashboards</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Productos</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-6  offset-md-3">
        <div class="card custom-card">
                <div class="card-header justify-content-between">
                    <div class="card-title">
                        Editar Categorias
                    </div>
                </div>
            <div class="card-body">
                <form action="{{ route('category.update', $category->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="row mb-3">
                        <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Codigo ID Google</label>
                        <div class="col-sm-3">
                            <input type="number" name="id_google" class="form-control form-control-sm" id="colFormLabelSm" value="{{ $category->id_google }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Categorias <br><sub>Separadas por comas</sub></label>
                        <div class="col-sm-10">
                            <textarea name="categories" id="categories" cols="50" rows="10"  class="form-control form-control-sm" pattern="^[0-9a-zA-Z]+(,[0-9a-zA-Z]+){0,11}$">{!! $category->categories !!}</textarea>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{{ route('category.index') }}" class="btn btn-default">Volver</a>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-xl-6  offset-md-3">
        <!-- Page Header -->
        <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
            <h1 class="page-title fw-semibold fs-18 mb-0">Productos Google/Facebook</h1>
            <div class="ms-md-1 ms-0">
                <nav>
                    <ol class="breadcrumb mb-0">
                        <li class="breadcrumb-item"><a href="#">Dashboards</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Productos</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
  <!-- Start::row-1 -->
  <div class="row">
    <div class="col-xl-6  offset-md-3">
        <div class="card custom-card">
                <div class="card-header justify-content-between">
                    <div class="card-title">
                        Categorias
                    </div>
                    <a href="{{ route('category.create') }}" class="btn btn-primary">Nueva Categoria</a>
                </div>
            <div class="card-body">
                <table class="table table-responsive mb-0" id="categories-table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Categorias</th>
                            <th>ID Google</th>
                            <th>opcion</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<!--End::row-1 -->

@endsection
@include('assets.datatables')
@push('scripts')
<script>
    $(function() {
        $('#categories-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('category.data') !!}',
            columns: [
                {
                    data: 'id',
                    name: 'id'
                },
                { 
                    data: 'categories',
                    name: 'categories'
                },
                { 
                    data: 'id_google',
                    name: 'id_google'
                },
                {
                    data: 'options',
                    name: '',
                    orderable: false,
                    searchable: false
                }

            ],
            order: [
                [0, 'asc']
            ]
        });

      
    });
</script>
@endpush