routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('auth.login');
});

// Auth::routes();
require __DIR__ . '/auth.php';

// Route::get('/', 'HomeController@index');
Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', 'HomeController@index')->name('home');

    Route::group(['prefix' => 'order'], function () {
        Route::name('order.')->group(function () {
            // Route::get('/ordenes', 'OrderController@index');
            Route::get('order/{id_orden}', 'OrderController@show')->name('show');
            Route::get('/orders/get-orders', 'OrderController@getOrders')->name('data');
            Route::post('/order/factura', 'OrderController@facturar')->name('facturar');
            Route::post('/order/cancel', 'OrderController@cancelOrder')->name('cancel');
            Route::post('/send-hermes', 'OrderController@sendToHermes')->name('hermes');
            Route::get('/order/fechas', 'CancelationController@cancelation')->name('cancelation');
            Route::post('/order/add-hermesid', 'OrderController@addHermesId')->name('hermesid');
            Route::post('/order/add-rfc', 'OrderController@addRFC')->name('add-rfc');
            Route::get('/resend-webhook', 'OrderController@resendWebHook');
            Route::post('notacredito', 'OrderController@notacredito')->name('notacredito');
            Route::post('/creditNote', 'OrderController@creditNote')->name('gen_nc');
            Route::get('/{orderId}/nota-credito/{folio}', 'OrderController@showCreditNote')->name('show_nc');
            Route::post('/download', 'SoapController@download')->name('download');
            Route::post('/order/update-date', 'OrderController@updateDateOrder')->name('updateDate');
            
        });
        Route::group(['prefix' => 'address'], function () {
            Route::name('address.')->group(function () {
                Route::get('/address/{id}', 'AddressController@edit')->name('edit');
                Route::put('/address/{id}', 'AddressController@update')->name('update');
            });
        });
        Route::post('/product/delete', 'ProductController@delete')->name('product.delete');
    });

    Route::prefix('products')->group(function () {
        Route::name('product.')->group(function () {
            Route::get('/list-feed', 'ProductFeedController@index')->name('feed');
            Route::get('/get-feed-products', 'ProductFeedController@getDataProducts')->name('data');
            Route::get('/product-feed/export/csv', 'ProductFeedController@export_csv')->name('export_feed.csv');
            Route::get('/product-feed/export/excel', 'ProductFeedController@export_excel')->name('export_feed.excel');
        });
    });

    Route::prefix('categories')->group(function () {
        Route::name('category.')->group(function () {
            Route::get('/', 'GoogleCategoryController@index')->name('index');
            Route::get('/edit/{id}', 'GoogleCategoryController@edit')->name('edit');
            Route::get('/create', 'GoogleCategoryController@create')->name('create');
            Route::post('/store', 'GoogleCategoryController@store')->name('store');
            Route::put('/update/{id}', 'GoogleCategoryController@update')->name('update');
            Route::get('/get-categories', 'GoogleCategoryController@getCategories')->name('data');
        });
    });

    Route::group(['middleware' => ['role:Super Admin']], function () {
        Route::group(['prefix' => 'user'], function () {
            Route::name('user.')->group(function () {
                Route::get('/all', 'UserController@index')->name('list');
                Route::get('/create', 'UserController@create')->name('create');
                Route::post('/store', 'UserController@store')->name('store');
                Route::get('/edit/{id}', 'UserController@edit')->name('edit');
                Route::put('/update/{id}', 'UserController@update')->name('update');
                Route::delete('/delete', 'UserController@destroy')->name('destroy');
            });
        });
    });

    Route::get('buscar', 'OrderController@buscar')->name('search');

// Route::get('/n3YnkUWXXhUktQhP8PLH', function () {
    //     Artisan::call('canclation:cron');
    //     return 'OK';
    // });

    Route::get('/newsletter', 'NewsletterController@index')->name('newsletter');
    Route::get('/newsletter/old', 'NewsletterController@oldRegisters')->name('newsletter.old');
    Route::get('/newsletter/get-registers', 'NewsletterController@getRegisters')->name('newsletter.data');
    Route::get('/newsletter/get-registers-old', 'NewsletterController@getNewsletter')->name('newsletter.data.old');

    Route::get('qry', 'OrderController@address');

});
Route::get('/w0nXLI2WgFrCdycwvFaJ', 'CancelationController@Cancelar');
Route::get('/sin-hermesid', 'OrderController@sendHermesData');
Route::get('/ade921176492a307745bf24a8e055a3a', 'ChatBotController@getProductsFeed');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    const CREATED_AT = 'created';
    const UPDATED_AT = 'updated';

    protected $table = 'order_products';
    protected $primaryKey = 'id';
    public $timestamps = false;
    protected $filable = [
        'line_item_id', 'id_orden', 'codigo_alfa', 'sku', 'cantidad', 'devolucion',
        'envio', 'cancelacion', 'nota_credito', 'importe', 'product_status', 'referencia',
        'talla', 'title', 'total_discount', 'variant_title', 'facturado',
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\OrderProductNc;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function delete(Request $request)
    {
        try {
            $id_product = $request->input('id');
            $qty = $request->input('cantidad');
            $product_nc = $this->updateItemProductNc($id_product, $qty);
            $product = $this->updateItemProduct($id_product, $qty);
            if($product){
                return response()->json(['ok' => false, 'icon' => 'warning', 'msg' => 'La cantidad ingresada no puede ser mayor a la cantidad del articulo a devolver.']);
            }
            
            // return response()->json(['ok' => true, 'icon' => 'success', 'msg' => $nc_qty], 200);
            return response()->json(['ok' => true, 'icon' => 'success', 'msg' => 'Estatus de articulo cambiado correctamente'], 200);
        } catch (\Throwable $th) {
            return response()->json(['ok' => false, 'icon' => 'error', 'msg' => 'Error al intentar cambiar el estatus del articulo'], 200);
        }

    }

    public function refundShopify($id_orden, $line_item_id, $qty)
    {
        $jsonStr = '{"refund":{"shipping":{"full_refund":true},"refund_line_items":[{"line_item_id":' . $line_item_id . ',"quantity":' . $qty . ',"restock_type":"no_restock"}]}}';

        $url = "https://" . config('app.api_key') . ":" . config('app.api_pass') . "@" . config('app.shop_name') . ".myshopify.com/admin/api/" . config('app.api_ver') . "/orders/" . $id_orden . "/refunds.json";
        $curl = curl_init($url);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $jsonStr);
        curl_setopt($curl, CURLOPT_HTTPHEADER, array("Content-Type: application/json"));
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
        $json_response = curl_exec($curl);
        curl_close($curl);

        $array_response = json_decode($json_response, true);

        if ($array_response['errors']) {
            return true;
        } else {
            return false;
        }
    }

    public function updateItemProduct($item_id, $qty)
    {
            $product = Product::where('line_item_id', '=', $item_id)->first();
            $nc_qty = $qty + $product->nota_credito;

            if ($qty == 0 || $nc_qty > $product->cantidad) {
                return true;
            }
            $product->nota_credito = $nc_qty;
            $product->product_status = 'nota_credito';
            $product->save();

            return false;

    }

    public function updateItemProductNc($item_id, $qty)
    {
        $product = OrderProductNc::where('line_item_id', '=', $item_id)->first();
        $product->cantidad = $qty;
        $product->update();

        return true;
    }
}

resources/views/products/product_feed.blade.php
@extends('layouts.app')

@section('content')
   <!-- Page Header -->
   <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
    <h1 class="page-title fw-semibold fs-18 mb-0">Productos Google/Facebook</h1>
    <div class="ms-md-1 ms-0">
        <nav>
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item"><a href="#">Dashboards</a></li>
                <li class="breadcrumb-item active" aria-current="page">Productos</li>
            </ol>
        </nav>
    </div>
</div>

  <!-- Start::row-1 -->
  <div class="row">
    <div class="col-xl-12">
        <div class="card custom-card">
                <div class="card-header justify-content-between">
                    <div class="card-title">
                        Productos Google/Facebook
                    </div>
                    <div>
                        <a href="{{ route('product.export_feed.csv') }}" class="btn btn-primary">Exportar CSV</a>
                        <a href="{{ route('product.export_feed.excel') }}" class="btn btn-primary">Exportar Excel</a>
                    </div>
                </div>
            <div class="card-body">
                <table class="table table-responsive mb-0" id="products-table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>MODELO</th>
                            <th>URL PROD.</th>
                            <th>ESTADO</th>
                            <th>URL IMG</th>
                            <th>PRECIO</th>
                            <th>PRECIO OFERT.</th>
                            <th>FECHA PROM.</th>
                            <th>MARCA</th>
                            <th>MATERIAL</th>
                            <th>DISPONIBILIDAD</th>
                            <th>STOCK</th>
                            <th>GENERO</th>
                            <th>EDAD</th>
                            <th>CATEGORIA</th>
                            <th>CATEGORIA ID</th>
                            <th>APLAZO</th>
                            <th>TALLA</th>
                            <th>SIST. TALLA</th>
                            <th>UPC BARCODE</th>
                            <th>COLOR</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<!--End::row-1 -->

@endsection
@include('assets.datatables')
@push('scripts')
<script>
    $(function() {
        $('#products-table').DataTable({
            scrollX: true,
            processing: true,
            serverSide: true,
            ajax: '{!! route('product.data') !!}',
            columns: [
                {
                    data: 'id',
                    name: 'id'
                },
                { 
                    data: 'nombre',
                    name: 'nombre'
                },
                { 
                    data: 'url_product',
                    name: 'url_product'
                },
                { 
                    data: 'estado',
                    name: 'estado'
                },
                { 
                    data: 'url_imagen',
                    name: 'url_imagen'
                },
                { 
                    data: 'precio',
                    name: 'precio'
                },
                { 
                    data: 'precio_oferta',
                    name: 'precio_oferta'
                },
                { 
                    data: 'fecha_promo',
                    name: 'fecha_promo'
                },
                { 
                    data: 'marca',
                    name: 'marca'
                },
                { 
                    data: 'material',
                    name: 'material'
                },
                { 
                    data: 'disponibilidad',
                    name: 'disponibilidad'
                },
                { 
                    data: 'stock',
                    name: 'stock'
                },
                { 
                    data: 'genero',
                    name: 'genero'
                },
                { 
                    data: 'edad',
                    name: 'edad'
                },
                { 
                    data: 'categoria',
                    name: 'categoria'
                },
                { 
                    data: 'categoria_2',
                    name: 'categoria_2'
                },
                { 
                    data: 'installment_amount',
                    name: 'installment_amount'
                },
                { 
                    data: 'talla',
                    name: 'talla'
                },
                { 
                    data: 'sistema_talla',
                    name: 'sistema_talla'
                },
                { 
                    data: 'upc_barcode',
                    name: 'upc_barcode'
                },
                { 
                    data: 'color',
                    name: 'color'
                }

            ],
            order: [
                [2, 'desc']
            ]
        });

      
    });
</script>
@endpush